version: '3.3'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'zequipments-erp-db'
      MYSQL_USER: 'zequipments-user'
      MYSQL_PASSWORD: 'zequipments-password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
